/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GuestPanel.java
 *
 * Created on Nov 28, 2011, 9:24:01 PM
 */
package lab7;

import java.sql.*;
import javax.swing.JFrame;

/**
 *
 * @author srbecker
 */
public class GuestPanel extends javax.swing.JPanel
{
  private Connection conn;
  private Guest guest;
  private JFrame ContentPane;

  /** Creates new form OwnerPanel */
  public GuestPanel()
  {
    initComponents();
  }

  public void addConnection(Connection c)
  {
    this.conn = c;
    this.guest = new Guest(c);
    this.ContentPane = new JFrame();
    this.ContentPane.setSize(900, 600);
    this.ContentPane.setVisible(false);
  }



  private void RoomsRatesButtonActionPerformed(java.awt.event.ActionEvent evt) {

    System.out.println("Clicked Rooms/Rates Button");
    //RoomsRatesPanel rooms_rates = new RoomsRatesPanel(guest);
    //ContentPane.setContentPane(rooms_rates);
    ContentPane.setVisible(true);


}


private void Reservations2ButtonActionPerformed(java.awt.event.ActionEvent evt) {

    System.out.println("Reservations Button");
    Reservations2Panel reservations2 = new Reservations2Panel();
    ContentPane.setContentPane(reservations2);
    ContentPane.setVisible(true);
}


    // Variables declaration - do not modify
    private javax.swing.JButton Reservations2Button;
    private javax.swing.JButton RoomsRatesButton;
    private javax.swing.JButton jButton4;
    //private javax.swing.JLabel jLabel1;
    // End of variables declaration



  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */

@SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();

    setMinimumSize(new java.awt.Dimension(700, 400));
    setName("Form"); // NOI18N
    setPreferredSize(new java.awt.Dimension(700, 400));

    org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(lab7.Lab7App.class).getContext().getResourceMap(GuestPanel.class);
    jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
    jLabel1.setName("jLabel1"); // NOI18N

    org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(layout.createSequentialGroup()
        .addContainerGap()
        .add(jLabel1)
        .addContainerGap(644, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(layout.createSequentialGroup()
        .addContainerGap()
        .add(jLabel1)
        .addContainerGap(364, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel jLabel1;
  // End of variables declaration//GEN-END:variables
}
