/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * OwnerPanel.java
 *
 * Created on Nov 28, 2011, 9:23:09 PM
 */
package lab7;

import java.sql.*;
import javax.swing.JFrame;

/**
 *
 * @author marcus
 */
public class OwnerPanel extends javax.swing.JPanel
{
  private Connection conn;
  private Owner owner;
  private JFrame ContentPane;
  
  /** Creates new form OwnerPanel */
  public OwnerPanel()
  {
    initComponents();
  }
  
  public void addConnection(Connection c)
  {
    this.conn = c;
    this.owner = new Owner(c);
    this.ContentPane = new JFrame();
    this.ContentPane.setSize(900, 600);
    this.ContentPane.setVisible(false);
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        OccupancyButton = new javax.swing.JButton();
        RevenueButton = new javax.swing.JButton();
        ReservationsButton = new javax.swing.JButton();
        RoomsButton = new javax.swing.JButton();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(lab7.Lab7App.class).getContext().getResourceMap(OwnerPanel.class);
        jButton4.setText(resourceMap.getString("jButton4.text")); // NOI18N
        jButton4.setName("jButton4"); // NOI18N

        setMinimumSize(new java.awt.Dimension(700, 400));
        setName("Form"); // NOI18N
        setPreferredSize(new java.awt.Dimension(700, 400));

        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        OccupancyButton.setFont(resourceMap.getFont("OccupancyButton.font")); // NOI18N
        OccupancyButton.setText(resourceMap.getString("OccupancyButton.text")); // NOI18N
        OccupancyButton.setName("OccupancyButton"); // NOI18N
        OccupancyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OccupancyButtonActionPerformed(evt);
            }
        });

        RevenueButton.setFont(resourceMap.getFont("RevenueButton.font")); // NOI18N
        RevenueButton.setText(resourceMap.getString("RevenueButton.text")); // NOI18N
        RevenueButton.setName("RevenueButton"); // NOI18N
        RevenueButton.setPreferredSize(new java.awt.Dimension(133, 25));
        RevenueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RevenueButtonActionPerformed(evt);
            }
        });

        ReservationsButton.setFont(resourceMap.getFont("ReservationsButton.font")); // NOI18N
        ReservationsButton.setText(resourceMap.getString("ReservationsButton.text")); // NOI18N
        ReservationsButton.setName("ReservationsButton"); // NOI18N
        ReservationsButton.setPreferredSize(new java.awt.Dimension(133, 25));
        ReservationsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReservationsButtonActionPerformed(evt);
            }
        });

        RoomsButton.setFont(resourceMap.getFont("RoomsButton.font")); // NOI18N
        RoomsButton.setText(resourceMap.getString("RoomsButton.text")); // NOI18N
        RoomsButton.setName("RoomsButton"); // NOI18N
        RoomsButton.setPreferredSize(new java.awt.Dimension(133, 25));
        RoomsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoomsButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(OccupancyButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 143, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(RevenueButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 149, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(ReservationsButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 146, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(RoomsButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 147, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(252, 252, 252)
                        .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 182, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 67, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(OccupancyButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                    .add(RevenueButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                    .add(ReservationsButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                    .add(RoomsButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE))
                .add(38, 38, 38))
        );

        OccupancyButton.getAccessibleContext().setAccessibleName(resourceMap.getString("jButton1.AccessibleContext.accessibleName")); // NOI18N
    }// </editor-fold>//GEN-END:initComponents

private void OccupancyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OccupancyButtonActionPerformed

    System.out.println("Clicked Occupancy Button");   
    OccupancyPanel occupancy = new OccupancyPanel(owner);
    ContentPane.setContentPane(occupancy);
    ContentPane.setVisible(true);   
    
    
}//GEN-LAST:event_OccupancyButtonActionPerformed

private void RevenueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RevenueButtonActionPerformed
    
    System.out.println(01 == 1);
    RevenuePanel revenue = new RevenuePanel();
    ContentPane.setContentPane(revenue);
    ContentPane.setVisible(true);
    
}//GEN-LAST:event_RevenueButtonActionPerformed

private void ReservationsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReservationsButtonActionPerformed

    System.out.println("Reservations Button");
    ReservationsPanel reservations = new ReservationsPanel();
    ContentPane.setContentPane(reservations);
    ContentPane.setVisible(true);
}//GEN-LAST:event_ReservationsButtonActionPerformed

private void RoomsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoomsButtonActionPerformed

    System.out.println("Rooms Button");
    RoomsPanel rooms = new RoomsPanel();
    ContentPane.setContentPane(rooms);
    ContentPane.setVisible(true);
}//GEN-LAST:event_RoomsButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OccupancyButton;
    private javax.swing.JButton ReservationsButton;
    private javax.swing.JButton RevenueButton;
    private javax.swing.JButton RoomsButton;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
