/*
 * RevenuePanel.java
 *
 * Marcus Ortiz
 */
package lab7;

import java.awt.event.ActionEvent;
import java.sql.Connection;
import javax.swing.*;

/**
 *
 * @author spartan
 */
public class RevenuePanel extends javax.swing.JPanel
{
  private Revenue model;
  
  private class Refresher implements java.awt.event.ActionListener
  {
    private RevenuePanel view;
    
    public Refresher(RevenuePanel view)
    {
      this.view = view;
    }
    
    public void actionPerformed(ActionEvent ae)
    {
      //System.out.println("refresh!");
      view.refreshTable();
    }
  }

  /** Creates new form RevenuePanel */
  public RevenuePanel(Connection c)
  {
    this.model = new Revenue(c);
    initComponents();
    
    this.revenueOption.addActionListener(new Refresher(this));
    this.reservationsOption.addActionListener(new Refresher(this));
    
    this.displayOptions.add(this.revenueOption);
    this.displayOptions.add(this.reservationsOption);
    
    refreshTable();
  }
  
  private void refreshTable()
  {
    if(true) return; // remove me later
    
    if(this.revenueOption.isSelected())
    {
      System.out.println("rev selected");
      JTable table = new JTable(this.model.getRevTable());
      this.tableContainer.setViewportView(table);
      table.setFillsViewportHeight(true);
    }
    else if(this.reservationsOption.isSelected())
    {
      System.out.println("res selected");
      JTable table = new JTable(this.model.getResTable());
      this.tableContainer.setViewportView(table);
      table.setFillsViewportHeight(true);
    }
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    displayOptions = new javax.swing.ButtonGroup();
    titleLabel = new javax.swing.JLabel();
    tableContainer = new javax.swing.JScrollPane();
    revenueOption = new javax.swing.JRadioButton();
    reservationsOption = new javax.swing.JRadioButton();

    setName("Form"); // NOI18N
    setPreferredSize(new java.awt.Dimension(900, 600));

    org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(lab7.Lab7App.class).getContext().getResourceMap(RevenuePanel.class);
    titleLabel.setFont(resourceMap.getFont("titleLabel.font")); // NOI18N
    titleLabel.setText(resourceMap.getString("titleLabel.text")); // NOI18N
    titleLabel.setName("titleLabel"); // NOI18N

    tableContainer.setName("tableContainer"); // NOI18N

    revenueOption.setSelected(true);
    revenueOption.setText(resourceMap.getString("revenueOption.text")); // NOI18N
    revenueOption.setName("revenueOption"); // NOI18N

    reservationsOption.setText(resourceMap.getString("reservationsOption.text")); // NOI18N
    reservationsOption.setName("reservationsOption"); // NOI18N

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(tableContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 860, Short.MAX_VALUE)
            .addContainerGap())
          .addGroup(layout.createSequentialGroup()
            .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(306, 306, 306))
          .addGroup(layout.createSequentialGroup()
            .addComponent(revenueOption)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(reservationsOption)
            .addContainerGap(677, Short.MAX_VALUE))))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(revenueOption)
          .addComponent(reservationsOption))
        .addGap(41, 41, 41)
        .addComponent(tableContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(32, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.ButtonGroup displayOptions;
  private javax.swing.JRadioButton reservationsOption;
  private javax.swing.JRadioButton revenueOption;
  private javax.swing.JScrollPane tableContainer;
  private javax.swing.JLabel titleLabel;
  // End of variables declaration//GEN-END:variables
}
